version: '3'
services:
  redis:
    image: "redis:3.0.6"
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: localhost
      REDIS_PASSWORD: redis_pass
  mongodb_container:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
  rabbitmq-stomp:
    build:
      context: .
      dockerfile: rabitmq/Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
